import type { Metadata } from "next";
import "./globals.css";
import { inter } from "@/ui/font";

export const metadata: Metadata = {
  title: "Invitacion Virtual",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased bg-primary-400`}>
        {children}
      </body>
    </html>
  );
}
